import { useState } from 'react';
import { useParams } from 'react-router-dom';
import bannerDefault from '../assets/banner-example.png';
import NavigationBar from '../components/NavigationBar';
import ExploreCard from '../components/ExploreCard';
import iconUser from '../assets/noun-user-1256674.png';
import iconTime from '../assets/noun-time-1232961.png';


function BlogPost() {
	const { id } = useParams();
	const [bannerImg, setBannerImg] = useState(bannerDefault);
	return (
		<div className="w-full min-h-screen bg-neutral-00 flex flex-col items-center overflow-hidden">
			<NavigationBar page="blogPost" />
			<section className="w-full max-w-[82.5rem] bg-white h-40 sm:h-48 md:h-52 lg:h-56 flex">
				<img
					className="w-full object-cover object-center"
					src={bannerImg}
					alt="Post's Banner"
				/>
			</section>
			<section className="w-full max-w-[82.5rem] grid grid-cols-12 mb-7">
				<div className="col-span-full md:col-span-8 lg:col-span-9 px-5 lg:pr-7">
					<div className="flex mt-5 mb-5 md:px-3 md:mt-7 lg:px-4">
						<div className="flex items-center">
							{/* user icon created by Kirsh from the Noun Project */}
							<img className="mr-1 h-6 w-fit" src={iconUser} alt="user" />
							<p>Blog Admin</p>
						</div>
						<div className="flex items-center">
							{/* time icon created by Trident from the Noun Project */}
							<img className="ml-4 mr-1 h-6 w-fit" src={iconTime} alt="time posted" />
							<p>13-3-2023</p>
						</div>
					</div>
					<div className="w-full md:pl-3 lg:pl-4">
						{/* this is placeholder content */}
						<h1 className="font-heading font-bold text-2xl mb-3">
							Random Number Generator {id}
						</h1>
						<p>
							Various imaginative ways of collecting this entropic information have
							been devised. One technique is to run a hash function against a frame of
							a video stream from an unpredictable source. Lavarand used this
							technique with images of a number of lava lamps. HotBits measures
							radioactive decay with Geiger–Muller tubes, while Random.org uses
							variations in the amplitude of atmospheric noise recorded with a normal
							radio.
							<br />
							<br />
							Another common entropy source is the behavior of human users of the
							system. While people are not considered good randomness generators upon
							request, they generate random behavior quite well in the context of
							playing mixed strategy games.
							<br />
							<br />
							Most computer generated random numbers use PRNGs which are algorithms
							that can automatically create long runs of numbers with good random
							properties but eventually the sequence repeats (or the memory usage
							grows without bound). These random numbers are fine in many situations
							but are not as random as numbers generated from electromagnetic
							atmospheric noise used as a source of entropy. The series of values
							generated by such algorithms is generally determined by a fixed number
							called a seed. One of the most common PRNG is the linear congruential
							generator, which uses the recurrence.
							<br />
							<br />A simple pen-and-paper method for generating random numbers is the
							so-called middle-square method suggested by John von Neumann. While
							simple to implement, its output is of poor quality. It has a very short
							period and severe weaknesses, such as the output sequence almost always
							converging to zero. A recent innovation is to combine the middle square
							with a Weyl sequence. This method produces high quality output through a
							long period.
							<br />
							<br />
							Most computer programming languages include functions or library
							routines that provide random number generators. They are often designed
							to provide a random byte or word, or a floating point number uniformly
							distributed between 0 and 1.
						</p>
					</div>
				</div>
				<div className="col-span-full md:col-span-4 lg:col-span-3 px-4 sm:px-5 md:pl-0">
					<h3 className="font-heading text-lg font-bold tracking-wider mt-5">
						Explore Other Post
					</h3>
					<div className="w-full h-[0.2rem] bg-theme-purple mb-3" />
					<div className="w-full grid sm:grid-cols-2 md:grid-cols-1 gap-2 justify-items-center">
						<ExploreCard id='995'/>
						<ExploreCard id='996'/>
						<ExploreCard id='997'/>
						<ExploreCard id='998'/>
					</div>
				</div>
			</section>
		</div>
	);
}

export default BlogPost;
